### ISSUE TITLE
Link directly to a specific talk

### ISSUE THREAD

**Issue by calmrat** [devconfcz/devconf-cz-web#1]
Is there a way to directly link to a certain talk? I can just get the overview at https://devconf.cz/schedule.html but I would like to have a link directly to a talk if possible? (Adrian Reber)

**Comment by danielpassos** [comment]
Done!

You need to pass the id using #id-number

https://devconf-cz-2017.firebaseapp.com/sessions#183

But it doesn't work from now on the website because `iframe` need to pass the id parameter for the session/iframe page.
